// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjlhTFLqNjdXvKDjQyXWaSVFEJY5FaT94',
    appId: '1:188508721319:web:7b15f070d63b196a244b82',
    messagingSenderId: '188508721319',
    projectId: 'farmedge-56629',
    authDomain: 'farmedge-56629.firebaseapp.com',
    storageBucket: 'farmedge-56629.firebasestorage.app',
    measurementId: 'G-QM90Y4WF1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxvJ5wp4I4I_UoKuJtSfVkClmAHJ_LCE',
    appId: '1:188508721319:android:e2481fcd3927efd7244b82',
    messagingSenderId: '188508721319',
    projectId: 'farmedge-56629',
    storageBucket: 'farmedge-56629.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBMaJhyTRotQ8zRdfe97HxlTWMm_4D5E',
    appId: '1:188508721319:ios:af849032886cc250244b82',
    messagingSenderId: '188508721319',
    projectId: 'farmedge-56629',
    storageBucket: 'farmedge-56629.firebasestorage.app',
    iosBundleId: 'com.example.farmedge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBMaJhyTRotQ8zRdfe97HxlTWMm_4D5E',
    appId: '1:188508721319:ios:af849032886cc250244b82',
    messagingSenderId: '188508721319',
    projectId: 'farmedge-56629',
    storageBucket: 'farmedge-56629.firebasestorage.app',
    iosBundleId: 'com.example.farmedge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjlhTFLqNjdXvKDjQyXWaSVFEJY5FaT94',
    appId: '1:188508721319:web:cbc6804c056a039d244b82',
    messagingSenderId: '188508721319',
    projectId: 'farmedge-56629',
    authDomain: 'farmedge-56629.firebaseapp.com',
    storageBucket: 'farmedge-56629.firebasestorage.app',
    measurementId: 'G-FYSN09GBEG',
  );

}